### ISSUE TITLE
How do add dynamic pages?

### ISSUE THREAD

**Issue by 28development** [jakeprins/nextjs-netlify-cms#2]
How would I need to add dynamic pages, if one uses a .yaml file one can use something like this

```
collections:
  - name: 'support'
    label: 'Support'
    folder: '_support/component'
    path: '{{slug}}/index'
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
```

how would that translate to the config.js file
